baseurl = "https://netdevops.me/"
buildDrafts = true
metadataFormat = "yaml"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "NetDevOps"
theme = "uBlogger"

enableGitInfo = true
enableEmoji = true

[permalinks]
  posts = "/:year/:title/"

# [author]
#   name = "netdevops"


[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2

# Markup related configuration in Hugo
[markup]
  defaultMarkdownHandler = "goldmark"
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
      # xhtml = true

[params]
# uBlogger theme version
  version = "2.0.X"

  description = "DevOps applied to networking"

  # Your favicon path, default is "/favicon.png"
  favicon = "/images/ntdvps_ico64.png"

  [params.page]
    [params.page.toc]
      auto = false
    [params.page.code]
      maxShownLines = 20

  [params.page.library]
      [params.page.library.css]
        # located in "assets/"
        someCSS = "drawio.css"

  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "https://cdn.jsdelivr.net/gh/hellt/netdevops.me@master/static/images/me.jpeg"
      title = "Applying DevOps to networking"
      subtitle = "Hey, thanks for coming over. Here you'll find my notes and knowledge sharing on things around Network automation, k8s and public clouds, sprinkled with some software I occasionally write or contribute to."
      social = true
      # disclaimer (HTML format is supported)
      # disclaimer = "test"

  [params.comment]
    enable = true
    [params.comment.utterances]
      enable = true
      repo = "hellt/netdevops.me"
      issueTerm = "pathname"
      label = "comment"
      lightTheme = "github-light"
      darkTheme = "github-dark"

  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "algolia"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = "Search..."
    #  max number of results length
    maxResultLength = 10
    #  snippet length of the result
    snippetLength = 60
    #  HTML tag name of the highlight part in results
    highlightTag = "em"
    #  whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = "blog"
      appID = "H1AI8QKFEK"
      searchKey = "0544bc3c928ba0e387c3b3353112e43d"

  [params.page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = true

  # Footer config
  [params.footer]
    enable = true
    # uBlogger NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # uBlogger NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # uBlogger NEW | 0.2.0 whether to show copyright info
    copyright = true
    # uBlogger NEW | 0.2.0 whether to show the author
    author = false
    # Site creation time
    since = 2015
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.social]
    GitHub = "hellt"
    Twitter = "ntdvps"
    Linkedin = "rdodin"

  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "UA-101537614-1"
      anonymizeIP = false

[outputs]
  home = ["HTML", "RSS", "JSON"]