baseurl = "https://netdevops.me/"
buildDrafts = true
metadataFormat = "yaml"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "NetDevOps"
theme = "uBlogger"
googleAnalytics = "UA-101537614-1"

# [author]
#   name = "Roman Dodin"
#   bio = "Eagerness to learn & passion to share"
#   job = "Network Automation @ Nokia"
#   location = "Netherlands"
#   # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
#   # gravatarEmail = "dodin.roman@gmail.com"
#   # Your profile picture
#   # Overwritten by your gravatar image if `author.gravatarEmail` is filled
#   picture = "https://gitlab.com/rdodin/pics/-/wikis/uploads/95361847e46716d94cd8469ae33eeed1/avatar.png"
#   # Your Twitter username without the @. E.g : thibaudlepretre
#   twitter = "@ntdvps"
#   # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
#   # googlePlus = "+ThibaudLepretre"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false

[params]
# uBlogger theme version
  version = "2.0.X"

  description = "DevOps applied to networking"

  # Your favicon path, default is "/favicon.png"
  favicon = "/images/ntdvps_ico64.png"

  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "algolia"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = "Search..."
    #  max number of results length
    maxResultLength = 10
    #  snippet length of the result
    snippetLength = 60
    #  HTML tag name of the highlight part in results
    highlightTag = "em"
    #  whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = "blog"
      appID = "H1AI8QKFEK"
      searchKey = "0544bc3c928ba0e387c3b3353112e43d"


[outputs]
  home = ["HTML", "RSS", "JSON"]