site_name: Applying DevOps to networks

docs_dir: blog

theme:
  name: material

  language: en

# Plugins
plugins:
  - blog:
      blog_dir: .
      post_url_date_format: yyyy
      archive: false
      categories: false
  - search:
      separator: '[\s\-\_]'
  - minify:
      minify_html: true

nav:
  - Blog:
      - index.md
