name: github pages

on:
  push:

env:
  MKDOCS_INS_VER: 8.5.3-insiders-4.23.6

jobs:
  docs-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: htmltest
        run: |
          curl https://htmltest.wjdp.uk | bash
          ./bin/htmltest -c htmltest.yml

  deploy:
    runs-on: ubuntu-20.04
    needs: docs-test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker run -v $(pwd):/docs --user $(id -u):$(id -g) --entrypoint mkdocs ghcr.io/srl-labs/mkdocs-material-insiders:$MKDOCS_INS_VER gh-deploy --force --strict
